app:
    resource: "@App/Resources/config/routing.yml"

rest:
    type: rest
    resource: "@Rest/Resources/config/routing.yml"
    prefix:   rest

article:
    resource: "@App/Controller/ArticleController.php"
    type:     annotation