timeline:
    type: rest
    resource: Rest\Controller\TimelineController
    name_prefix: rest_timeline_
      
article:
    type: rest
    resource: Rest\Controller\ArticleController
    name_prefix: rest_article_