editor_document:
    type: rest
    resource: Rest\Controller\Editor\DocumentController
    prefix: editor
    name_prefix: rest_editor_

editor_timeline:
    type: rest
    prefix: editor
    resource: Rest\Controller\Editor\TimelineController
    name_prefix: rest_editor_
      
editor_article:
    type: rest
    prefix: editor
    resource: Rest\Controller\Editor\ArticleController
    name_prefix: rest_editor_
    
viewer_document:
    type: rest
    prefix: viewer
    resource: Rest\Controller\Viewer\DocumentController
    name_prefix: rest_viewer_
  