# https://github.com/KnpLabs/geekweek12/wiki/Routing

app:
    pattern: /
    defaults: { _controller: App:Index:index }
  
App:Timeline:
    collections: [index, personal]
    resources: [show, update, delete, edit]